wanna-go-home/lens_review_ios

lens_review_ios.xcodeproj/project.pbxproj, lens_review_ios/BoardListView.swift, lens_review_ios/BoardListViewModel.swift, lens_review_ios/ContentView.swift, lens_review_ios/Network/APIBuilder.swift, lens_review_ios/Network/LensAPIClient.swift, lens_review_ios/Network/Model/Board.swift, lens_review_ios/lens_review_iosApp.swift
- 자유게시판 Model, View, ViewModel 추가
- Main View에서 자유게시판 리스트 뜨게 함
=> 자유게시판 API 연동

lens_review_ios.xcodeproj/project.pbxproj, lens_review_ios/ContentView.swift, lens_review_ios/Network/APIBuilder.swift, lens_review_ios/Network/LensAPIClient.swift, lens_review_ios/Network/Model/Review.swift, lens_review_ios/ReviewListView.swift, lens_review_ios/ReviewListViewModel.swift, lens_review_ios/lens_review_iosApp.swift
- 리뷰게시판 Model, View, ViewModel 추가
- Main View에서 리뷰게시판 리스트 뜨게 함
=> 리뷰게시판 API 연동

lens_review_ios.xcodeproj/project.pbxproj, lens_review_ios.xcworkspace/xcshareddata/swiftpm/Package.resolved, lens_review_ios/LensListView.swift, lens_review_ios/Network/Model/Lens.swift
- URL로부터 이미지 로드는 URLImage 사용 (URLImage : https://github.com/dmytro-anokhin/url-image)
=> Show lens productImage

lens_review_ios.xcodeproj/project.pbxproj, lens_review_ios.xcworkspace/xcshareddata/swiftpm/Package.resolved, lens_review_ios/BoardListView.swift, lens_review_ios/BoardListViewModel.swift, lens_review_ios/ContentView.swift, lens_review_ios/LensListViewModel.swift, lens_review_ios/LoginView.swift, lens_review_ios/LoginViewModel.swift, lens_review_ios/Network/APIBuilder.swift, lens_review_ios/Network/LensAPIClient.swift, lens_review_ios/Network/Model/FreeBoardPreview.swift, lens_review_ios/Network/Model/LensPreview.swift, lens_review_ios/Network/Model/Login.swift, lens_review_ios/Network/Model/ReviewBoardPreview.swift, lens_review_ios/ReviewListViewModel.swift, lens_review_ios/Utils/KeychainManager.swift, lens_review_ios/lens_review_iosApp.swift
- API Path 변경된 거 반영
- Login API 적용해서 token 받아오기
- token 관리는 Keychain-swift 사용 (https://github.com/evgenyneu/keychain-swift)
- HTTPHeader에 token 추가
- 이거 추가하면서 API 콜하는 위치 바꿨었는데, 중복 호출되는 버그 있어서 수정함 (commit 57d212e)
TO DO
- 자동 로그인
- 토큰 관리 관련
- 에러 핸들링
- 로그인 실패 시 처리
- 로그인 성공했지만 토큰이 없을 경우(가 있나?)
=> Login & API authorization

lens_review_ios/Network/APIBuilder.swift, lens_review_ios/Network/Model/LensPreview.swift
- Login API Request 변경
- account, pw를 Header로 넘기던 거에서 Body로 넘기도록 수정
- lens detail api 변경된 거 반경
- parameter에서 path로 변경
=> Login API Request 타입 변경(Header -> Body)

lens_review_ios/LensDetailView.swift, lens_review_ios/LensListView.swift, lens_review_ios/Network/Model/LensDetail.swift, lens_review_ios/Network/Model/LensPreview.swift
TODO
- spacing 값 조절(?)
- "그래픽 직경" 같은 String들 상수로 빼기
- 탭뷰 커스텀으로 해서 상단탭으로 바꾸기
=> Lens preview & detail UI

lens_review_ios.xcodeproj/project.pbxproj, lens_review_ios/Network/APIBuilder.swift, lens_review_ios/Network/LensAPIClient.swift, lens_review_ios/Network/Model/ReviewBoardDetail.swift, lens_review_ios/UI/LensDetail/LensDetailViewModel.swift, lens_review_ios/UI/ReviewBoard/ReviewListView.swift, lens_review_ios/UI/ReviewBoardDetail/ReviewBoardDetailView.swift, lens_review_ios/UI/ReviewBoardDetail/ReviewBoardDetailViewModel.swift
close https://github.com/wanna-go-home/Issue/issues/12
- Review Detail API 붙임
- Review Detail UI도 일단 자유게시판 그대로 함(+ 글 내용 밑에 이미지 추가)
=> Review detail API & UI

lens_review_ios/UI/ContentView.swift
close https://github.com/wanna-go-home/Issue/issues/39
- 상단 탭바로 변경
- swipe로 탭 이동 가능
=> Tab bar 위치 변경

lens_review_ios.xcodeproj/project.pbxproj, lens_review_ios/Network/APIBuilder.swift, lens_review_ios/Network/LensAPIClient.swift, lens_review_ios/Network/Model/FreeBoardComment.swift, lens_review_ios/UI/FreeBoardDetail/FreeBoardDetailView.swift, lens_review_ios/UI/FreeBoardDetail/FreeBoardDetailViewModel.swift, lens_review_ios/UI/LensList/LensListViewModel.swift
close https://github.com/wanna-go-home/Issue/issues/36
- API 동작 확인
=> Attach FreeBoard Comment/ChildComment GET API

lens_review_ios/Network/Model/FreeBoardDetail.swift, lens_review_ios/Network/Model/FreeBoardPreview.swift, lens_review_ios/UI/ContentView.swift, lens_review_ios/UI/FreeBoard/BoardListView.swift, lens_review_ios/UI/FreeBoard/Comment/CommentRowView.swift, lens_review_ios/UI/FreeBoard/Comment/CommentView.swift, lens_review_ios/UI/FreeBoard/Detail/FreeBoardDetailView.swift, lens_review_ios/UI/FreeBoard/Modify/ArticleModifyView.swift, lens_review_ios/UI/FreeBoard/Write/FreeBoardWriteView.swift, lens_review_ios/UI/LensDetail/LensDetailView.swift, lens_review_ios/UI/LensList/LensListView.swift, lens_review_ios/UI/Login/LoginView.swift, lens_review_ios/UI/ReviewBoard/ReviewListView.swift, lens_review_ios/UI/ReviewBoardDetail/ReviewBoardDetailView.swift, lens_review_ios/Utils/DateManager.swift, lens_review_ios/Utils/StringUtil.swift, lens_review_ios/ko.lproj/Localizable.strings
close https://github.com/wanna-go-home/Issue/issues/62
close https://github.com/wanna-go-home/Issue/issues/65
- "X 년, 개월, 일, 분 전"으로 뜨도록 calcCreatedBefore 함수 만들어서 적용
- 텍스트 그냥 박혀있던 것들 Localizable.strings 파일로 뺌
=> CreatedBefore & 다국어지원 적용

lens_review_ios.xcodeproj/project.pbxproj, lens_review_ios/Network/APIBuilder.swift, lens_review_ios/Network/LensAPIClient.swift, lens_review_ios/Network/Model/ArticleWriteRequest.swift, lens_review_ios/UI/FreeBoard/Write/FreeBoardWriteView.swift, lens_review_ios/ko.lproj/Localizable.strings
- post, put할 때 Model 사용하도록 수정함
오류 수정
- localizable 파일에 오타 수정
- 글쓰기 화면에서 네비게이션바 숨기기(customTitlebar 사용하기 때문)
=> Modify to use model when requesting

lens_review_ios/Network/APIBuilder.swift, lens_review_ios/Network/Model/FreeBoardComment.swift, lens_review_ios/Network/Model/FreeBoardDetail.swift, lens_review_ios/Network/Model/FreeBoardPreview.swift, lens_review_ios/UI/FreeBoard/Detail/FreeBoardDetailView.swift
close https://github.com/wanna-go-home/Issue/issues/114
isAuthor 받아오도록 모델 파라미터에 추가하고 적용함
=> Apply isAuthor

lens_review_ios.xcodeproj/project.pbxproj, lens_review_ios/UI/FreeBoard/Comment/ChildCommentRowView.swift, lens_review_ios/UI/FreeBoard/Comment/CommentRowView.swift, lens_review_ios/ko.lproj/Localizable.strings
- actionSheet 넣으면서 코드가 넘 길어져서 파일 분리함
- 빠른 머지 하겠음 ㅎ
=> Comment / Child-Comment VIEW 분리

lens_review_ios/UI/FreeBoard/Comment/ChildCommentRowView.swift, lens_review_ios/UI/FreeBoard/Comment/CommentRowView.swift, lens_review_ios/UI/FreeBoard/Comment/CommentView.swift, lens_review_ios/UI/FreeBoard/Comment/CommentViewModel.swift, lens_review_ios/UI/FreeBoard/Detail/FreeBoardDetailView.swift, lens_review_ios/UI/UIConstants.swift, lens_review_ios/UI/UIUtil.swift, lens_review_ios/ko.lproj/Localizable.strings
close https://github.com/wanna-go-home/Issue/issues/141
- 얘도 Comment랑 같은 방식으로 동작해서 뷰쪽 구조가 마음에 들지 않지만 나중에 같이 손봄(Comment랑 같이 사용되는 부분은 하나로 빼는것도 같이 손봐야함)
=> Child comment 쓰기/수정/삭제

lens_review_ios/Assets.xcassets/Color/PrimaryColor.colorset/Contents.json, lens_review_ios/Network/LensAPIClient.swift, lens_review_ios/UI/Login/LoginView.swift, lens_review_ios/UI/Login/LoginViewModel.swift, lens_review_ios/UI/UIConstants.swift, lens_review_ios/ko.lproj/Localizable.strings
resolve https://github.com/wanna-go-home/Issue/issues/15
- 로그인 실패 시 alert로 실패했다고 알려주도록 함
- 회원가입 버튼 넣고, 로그인 버튼 아래로 뺌
=> Add login error handling

lens_review_ios.xcodeproj/project.pbxproj, lens_review_ios/Network/APIBuilder.swift, lens_review_ios/Network/LensAPIClient.swift, lens_review_ios/Network/Model/UserInfo.swift, lens_review_ios/UI/MyPage/MyPageView.swift, lens_review_ios/UI/MyPage/MyPageViewModel.swift
close https://github.com/wanna-go-home/Issue/issues/122
=> MyPage API (GET /api/user/me)

lens_review_ios.xcodeproj/project.pbxproj, lens_review_ios/UI/Login/SignUp/SignUpView.swift, lens_review_ios/Utils/LogUtil.swift
일단 걍 간단하게 쓸 수 있게 logger 만들었음
View에서는 **LogUtil.logger.viewLog(log: "로그 내용")**
다른곳에서는 **LogUtil.logger.log(log: "로그 내용")** 으로 쓰면 됨!
type은 https://developer.apple.com/documentation/os/oslogtype 을 참조하면 됨
걍 찍히는거 확인만 하는거면 default로 두면 될듯
=> Add logger

lens_review_ios.xcodeproj/project.pbxproj, lens_review_ios/Network/APIBuilder.swift, lens_review_ios/Network/LensAPIClient.swift, lens_review_ios/Network/Model/FreeBoardPreview.swift, lens_review_ios/Network/NetConstants.swift, lens_review_ios/UI/MyPage/MyArticle/MyArticleView.swift, lens_review_ios/UI/MyPage/MyArticle/MyArticleViewModel.swift, lens_review_ios/UI/MyPage/MyPageView.swift
resolve https://github.com/wanna-go-home/Issue/issues/123
=> My article

lens_review_ios.xcodeproj/project.pbxproj, lens_review_ios/Assets.xcassets/article-comment.imageset/Contents.json, lens_review_ios/Assets.xcassets/article-comment.imageset/chat_bubble_outline-black-24dp.svg, lens_review_ios/Assets.xcassets/review-comment.imageset/Contents.json, lens_review_ios/Assets.xcassets/review-comment.imageset/trip_origin-black-24dp.svg, lens_review_ios/Network/APIBuilder.swift, lens_review_ios/Network/LensAPIClient.swift, lens_review_ios/Network/Model/Comment.swift, lens_review_ios/UI/FreeBoard/Comment/ChildCommentRowView.swift, lens_review_ios/UI/FreeBoard/Comment/CommentRowView.swift, lens_review_ios/UI/FreeBoard/Comment/CommentViewModel.swift, lens_review_ios/UI/FreeBoard/Detail/FreeBoardDetailView.swift, lens_review_ios/UI/MyPage/MyComment/MyCommentView.swift, lens_review_ios/UI/MyPage/MyComment/MyCommentViewModel.swift, lens_review_ios/UI/MyPage/MyPageView.swift, lens_review_ios/Utils/DateManager.swift
resolve https://github.com/wanna-go-home/Issue/issues/125
=> My comment

lens_review_ios/Network/Model/ReviewBoardDetail.swift, lens_review_ios/UI/ReviewBoard/ReviewListView.swift
- 리뷰 모델 업데이트
- 리뷰 리스트에 렌즈 이미지 보이도록 수정
=> 리뷰 보드에 렌즈 이미지 추가

lens_review_ios/UI/FreeBoard/BoardListView.swift, lens_review_ios/UI/ReviewBoard/ReviewListView.swift, lens_review_ios/UI/UIUtil.swift
- 리뷰 리스트에 글쓰기 버튼 추가
- 아티클/리뷰 리스트에서 FloatingButton 같이 쓰려고 FloatingButton을 UIUtil로 뺌
=> 리뷰 리스트에 글쓰기 버튼 추가(Floating Button)
